a1:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: a1
    joint_speed: 1.17
    motor:
        id: 1
        init: 512
        min: 0
        max: 1023
a2:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: a2
    joint_speed: 1.17
    motor:
        id: 2
        init: 512
        min: 0
        max: 1023
a3:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: a3
    joint_speed: 1.17
    motor:
        id: 3
        init: 512
        min: 0
        max: 1023
a4:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: a4
    joint_speed: 1.17
    motor:
        id: 4
        init: 512
        min: 0
        max: 1023
a5:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: a5
    joint_speed: 1.17
    motor:
        id: 5
        init: 512
        min: 0
        max: 1023
a6:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: a6
    joint_speed: 1.17
    motor:
        id: 6
        init: 512
        min: 0
        max: 1023
a7:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: a7
    joint_speed: 1.17
    motor:
        id: 7
        init: 512
        min: 0
        max: 1023

