# An example configuration where (2,3) and (4,5) are actuators
# restricted to move as pairs.

# The min and max of master and slave motors are flipped which causes the pairs
# make sure the motors are driven in opposite directions.

shoulder_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: shoulder
    motor:
        id: 1
        init: 512
        min: 0
        max: 1023

elbow_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: elbow
    motor_master:
        id: 2
        init: 512
        min: 0
        max: 1023
    motor_slave:
        id: 3
        init: 512
        min: 1023
        max: 0

wrist_tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: wrist_tilt
    motor_master:
        id: 4
        init: 512
        min: 0
        max: 1023
    motor_slave:
        id: 5
        init: 512
        min: 1023
        max: 0

wrist_roll_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: wrist_roll
    motor:
        id: 6
        init: 512
        min: 0
        max: 1023

claw_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: claw
    motor:
        id: 7
        init: 512
        min: 0
        max: 1023

